version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
      - php:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
    config:
      ignore_warnings: true
      file_extensions: "php"
  phpmd:
    enabled: true
    config:
      file_extensions: "php"
      rulesets: "cleancode,codesize,unusedcode,controversial,design,naming"
exclude_patterns:
  - ".bundle/"
  - "**/node_modules/*"
  - "**/vendor/"
  - "**/*.js"